import { Score } from './schema';

export const defaultScores: Score[] = [
  {
    id: '',
    type: 'PORTUGUÊS',
    student_id: '',
    class_id: '',
    year: 2024,
    score: [],
  },
  {
    id: '',
    type: 'MATEMÁTICA',
    student_id: '',
    class_id: '',
    year: 2024,
    score: [],
  },
  {
    id: '',
    type: 'HISTÓRIA',
    student_id: '',
    class_id: '',
    year: 2024,
    score: [],
  },
  {
    id: '',
    type: 'GEOGRAFIA',
    student_id: '',
    class_id: '',
    year: 2024,
    score: [],
  },
  {
    id: '',
    type: 'CIÊNCIAS',
    student_id: '',
    class_id: '',
    year: 2024,
    score: [],
  },
  {
    id: '',
    type: 'ARTES',
    student_id: '',
    class_id: '',
    year: 2024,
    score: [],
  },
  {
    id: '',
    type: 'INGLÊS',
    student_id: '',
    class_id: '',
    year: 2024,
    score: [],
  },
  {
    id: '',
    type: 'EDUCAÇÃO FÍSICA',
    student_id: '',
    class_id: '',
    year: 2024,
    score: [],
  },
  {
    id: '',
    type: 'ÉTICA',
    student_id: '',
    class_id: '',
    year: 2024,
    score: [],
  },
  {
    id: '',
    type: 'RELIGIÃO',
    student_id: '',
    class_id: '',
    year: 2024,
    score: [],
  },
];
